dist: trusty
sudo: true
language: python
python:
  - "3.4"
  - "3.5"
  # XXX re-enable after fixing tests
  #- "3.6"
matrix:
  include:
    - python: 2.7
      env: TARGET=check2
    # XXX re-enable after fixing all the lint issues
    #- python: 3.6
    #  env: TARGET=flake8
    # XXX Switch to 3.4 for coverage once trial works right.
    - python: 2.7
      env:
          TARGET=coverage
      before_script:
        - python2 -m pip install -U coverage
        - python2 -m pip install -U codecov
      script:
        - make $TARGET
      after_success:
        - codecov
# XXX cache the installs?
env:
  global:
    - TRIAL_ARGS=-j4
  matrix:
    - TARGET=check3
install:
  - pip install flake8
  # These match "make depends"
  - pip install twisted==16.4.0 mock==1.3.0 configobj==5.0.6 passlib==1.6.5 pycurl
  - pip install http://launchpad.net/python-distutils-extra/trunk/2.39/+download/python-distutils-extra-2.39.tar.gz
  # build & install python-apt
  - make pipinstallpythonapt
script:
  - make $TARGET PYTHON=python$TRAVIS_PYTHON_VERSION
